apiVersion: v1
kind: Pod
metadata:
  name: argocd-server
  namespace: argocd
spec:
  containers:
    - name: argocd-server
      image: argoproj/argocd:latest  # Replace with the version you need
      ports:
        - containerPort: 8080
        - containerPort: 443
      env:
        - name: ARGOCD_SERVER_REPO_SERVER
          value: "argocd-repo-server.argocd.svc.cluster.local"
      volumeMounts:
        - name: argocd-data
          mountPath: /data
  volumes:
    - name: argocd-data
      emptyDir: {}
